// FrontEnd/src/pages/register.jsx
import React from "react";
import { useState } from "react";
import { useRouter } from "next/router";

export default function RegisterPage() {
  // The form still collects firstName and lastName for display;
  // however, only username, password, and email (mapped to myEmail) are sent.
  const [user, setUser] = useState({ firstName: '', lastName: '', username: '', email: '', password: '' });
  const [errors, setErrors] = useState({});
  const [message, setMessage] = useState('');
  const router = useRouter();

  // Validate the form fields.
  const validate = () => {
    const newErrors = {};

    if (!user.username) {
      newErrors.username = 'Username is required.';
    } else if (user.username.length < 4) {
      newErrors.username = 'Minimum 4 characters required.';
    } else if (user.username.length > 20) {
      newErrors.username = 'Maximum 20 characters allowed.';
    } else if (!/^[a-zA-Z0-9_]+$/.test(user.username)) {
      newErrors.username = 'Only letters, numbers, and underscores allowed.';
    }

    if (!user.email) {
      newErrors.email = 'Email is required.';
    } else if (!/\S+@\S+\.\S+/.test(user.email)) {
      newErrors.email = 'Invalid email format.';
    }

    if (!user.firstName) {
      newErrors.firstName = 'First name is required.';
    } else if (!/^[a-zA-Z]+$/.test(user.firstName)) {
      newErrors.firstName = 'Only letters are allowed.';
    }

    if (!user.lastName) {
      newErrors.lastName = 'Last name is required.';
    } else if (!/^[a-zA-Z]+$/.test(user.lastName)) {
      newErrors.lastName = 'Only letters are allowed.';
    }

    if (!user.password) {
      newErrors.password = 'Password is required.';
    } else if (user.password.length < 8) {
      newErrors.password = 'Password must be at least 8 characters.';
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  // Send a POST request to the backend using the expected keys.
  const registerUser = async () => {
    try {
      // Create a payload matching your backend's expected fields:
      //   - username
      //   - password
      //   - primary_contact_email (mapped from our "email" field)
      const payload = {
        username: user.username,
        password: user.password,
        primary_contact_email: user.email,
      };

      const response = await fetch('http://localhost:8080/create-account', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(payload),
      });

      const result = await response.text();

      if (!response.ok) throw new Error(result);

      // On success, navigate to the home page.
      router.push('/');
    } catch (err) {
      if (err.message.includes('UNIQUE constraint failed: users.username')) {
        setErrors({ username: 'Sorry, that username is taken. Please try again.' });
      } else {
        setMessage('Registration failed. Please try again.');
      }
    }
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    setMessage('');
    if (validate()) {
      registerUser();
    }
  };

  return (
    <div className="grid grid-rows-[20px_1fr_20px] items-center justify-items-center min-h-screen p-8 pb-20 gap-16 sm:p-20 bg-blue-100">
      <main className="flex flex-col gap-8 row-start-2 items-center sm:items-start">
        <form onSubmit={handleSubmit} className="p-10 text-black bg-white rounded-lg shadow-md space-y-6">
          <div className="text-center mb-6">
            <img
              src="/PG-icon.png"
              alt="Parting Gifts Logo"
              className="mx-auto mb-4 w-24"
              onClick={() => router.push("/")}
            />
            <h1 className="text-xl font-bold text-black">Create an account!</h1>
          </div>

          <div className="flex flex-row space-x-8">
            <div className="flex flex-col flex-grow">
              <label htmlFor="firstName" className="block text-sm font-medium text-black">
                First Name
              </label>
              <input
                type="text"
                id="firstName"
                value={user.firstName}
                onChange={(e) => setUser({ ...user, firstName: e.target.value })}
                className="w-full px-3 py-2 mt-1 border rounded-md text-black focus:outline-none focus:ring focus:ring-blue-300"
                placeholder="Enter your first name"
                required
              />
              {errors.firstName && <div className="text-red-500 text-sm">{errors.firstName}</div>}
            </div>
            <div className="flex flex-col flex-grow">
              <label htmlFor="lastName" className="block text-sm font-medium text-black">
                Last Name
              </label>
              <input
                type="text"
                id="lastName"
                value={user.lastName}
                onChange={(e) => setUser({ ...user, lastName: e.target.value })}
                className="w-full px-3 py-2 mt-1 border rounded-md text-black focus:outline-none focus:ring focus:ring-blue-300"
                placeholder="Enter your last name"
                required
              />
              {errors.lastName && <div className="text-red-500 text-sm">{errors.lastName}</div>}
            </div>
          </div>

          <div className="mb-4">
            <label htmlFor="username" className="block text-sm font-medium text-black">
              Username
            </label>
            <input
              type="text"
              id="username"
              value={user.username}
              onChange={(e) => setUser({ ...user, username: e.target.value })}
              className="w-full px-3 py-2 mt-1 border rounded-md text-black focus:outline-none focus:ring focus:ring-blue-300"
              placeholder="Enter your username"
              required
            />
            {errors.username && <div className="text-red-500 text-sm">{errors.username}</div>}
          </div>

          <div className="mb-4">
            <label htmlFor="email" className="block text-sm font-medium text-black">
              Email
            </label>
            <input
              type="email"
              id="email"
              value={user.email}
              onChange={(e) => setUser({ ...user, email: e.target.value })}
              className="w-full px-3 py-2 mt-1 border rounded-md text-black focus:outline-none focus:ring focus:ring-blue-300"
              placeholder="Enter your email"
              required
            />
            {errors.email && <div className="text-red-500 text-sm">{errors.email}</div>}
          </div>

          <div className="mb-4">
            <label htmlFor="password" className="block text-sm font-medium text-black">
              Password
            </label>
            <input
              type="password"
              id="password"
              value={user.password}
              onChange={(e) => setUser({ ...user, password: e.target.value })}
              className="w-full px-3 py-2 mt-1 border rounded-md text-black focus:outline-none focus:ring focus:ring-blue-300"
              placeholder="Enter your password"
              required
            />
            {errors.password && <div className="text-red-500 text-sm">{errors.password}</div>}
          </div>

          <div className="w-full flex-row flex justify-end">
            <button
              type="submit"
              className="bg-[#00A9C5] text-white rounded-full py-2 px-8 hover:bg-[#0088A3] focus:outline-none"
            >
              Register
            </button>
          </div>
          {message && <div className="text-red-500 text-sm">{message}</div>}
        </form>
      </main>
    </div>
  );
}

// FrontEnd/frontend/src/app/Components/Register/register.component.ts
// ------------------------------
// RegisterComponent (register.component.ts)
// ------------------------------
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';        // Provides support for template-driven forms.
import { CommonModule } from '@angular/common';       // Provides common Angular directives.
import { Router } from '@angular/router';             // Used for navigation between routes.
import { HttpClient } from '@angular/common/http';    // Used to send HTTP requests to the backend.

/*
  RegisterComponent manages user registration.
  It collects a username and password from the user, sends a registration request to the backend,
  and then navigates to the blank page with the username if registration is successful.
  It also provides navigation options for forgot password and login.
*/
@Component({
  selector: 'app-register',
  standalone: true,
  imports: [FormsModule, CommonModule],
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css']
})
export class RegisterComponent {
  user = { // Stores registration details.
    username: '',
    password: ''
  };
  message = ''; // Stores messages for user feedback.

  // The constructor injects Router for navigation and HttpClient for backend communication.
  constructor(private router: Router, private http: HttpClient) { }

  // register sends the user's registration details to the backend.
  // On success, it navigates to the blank page and passes the username.
  register() {
    this.http.post('http://localhost:8080/create-account', this.user, { responseType: 'text' })
      .subscribe({
        next: (response) => {
          console.log('Registration response:', response);
          this.message = response;
          setTimeout(() => {
            this.router.navigate(['/blank'], { state: { username: this.user.username } });
          }, 2000);
        },
        error: (err) => {
          console.error('Registration error:', err);
          if (err.error === "Registration failed: UNIQUE constraint failed: users.username\n") {
            this.message = 'Sorry, that username is taken. Please try again.';
          } else {
            this.message = 'Registration failed. Please try again.';
          }
        }
      });
  }

  // forgotPassword navigates to the forgot-password page.
  forgotPassword() {
    this.router.navigate(['/forgot-password']);
  }

  // goToLogin navigates to the login page.
  goToLogin() {
    this.router.navigate(['/login']);
  }
}

<div class="body">
    <form (ngSubmit)="register()" #registerForm="ngForm" class="form-container">
        <img src="https://i.postimg.cc/VsRBMLgn/pglogo.png" class="logo-img" alt="logo" />
        <p class="title">Create an account</p>

        <div class="input-container">
            <label for="username" class="input-label">Username</label>
            <input type="text" id="username" name="username" [(ngModel)]="user.username" required minlength="4"
                maxlength="20" pattern="^[a-zA-Z0-9_]+$" #username="ngModel" class="input-field" />
            <div *ngIf="username.invalid && username.touched" class="error-message">
                <div *ngIf="username.errors?.['required']">Username is required.</div>
                <div *ngIf="username.errors?.['minlength']">Minimum 4 characters required.</div>
                <div *ngIf="username.errors?.['maxlength']">Maximum 20 characters allowed.</div>
                <div *ngIf="username.errors?.['pattern']">Only letters, numbers, and underscores allowed.</div>
            </div>
        </div>

        <div class="input-container">
            <label for="password" class="input-label">Password</label>
            <input type="password" id="password" name="password" [(ngModel)]="user.password" required minlength="8"
                #password="ngModel" class="input-field" />
            <div *ngIf="password.invalid && password.touched" class="error-message">
                <div *ngIf="password.errors?.['required']">Password is required.</div>
                <div *ngIf="password.errors?.['minlength']">Password must be at least 8 characters.</div>
            </div>
        </div>

        <button type="submit" [disabled]="registerForm.invalid" class="submit-button">
            Register
        </button>
        <button type="button" (click)="forgotPassword()" class="forgot-button">
            Forgot my password?
        </button>
        <button type="button" (click)="goToLogin()" class="login-button">
            Already have an account? Login
        </button>

        <p *ngIf="message" class="error-message" style="padding-top: 10px;">
            {{ message }}
        </p>
    </form>
</div>
